languageCode = "en-us"
title = "Cupper Test"
baseURL = "https://jhung.github.io/cupper-test/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Testing **Cupper** for use with CMHR."
